// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlwh2J50wOfXxXsTx0ube3VIUOzXh1r4Q',
    appId: '1:599903397080:web:f056ccd40a1ff9e8d3e3ad',
    messagingSenderId: '599903397080',
    projectId: 'intelligentcounter-29709',
    authDomain: 'intelligentcounter-29709.firebaseapp.com',
    databaseURL: 'https://intelligentcounter-29709-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'intelligentcounter-29709.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAR8ai8Gv3a77UY4gcTFl93SC3veUEMbcE',
    appId: '1:599903397080:android:765fa9831131a48fd3e3ad',
    messagingSenderId: '599903397080',
    projectId: 'intelligentcounter-29709',
    databaseURL: 'https://intelligentcounter-29709-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'intelligentcounter-29709.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfO806O1GAHG7UAlbg5E828uLLCy2C4LI',
    appId: '1:599903397080:ios:609a8244b7064490d3e3ad',
    messagingSenderId: '599903397080',
    projectId: 'intelligentcounter-29709',
    databaseURL: 'https://intelligentcounter-29709-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'intelligentcounter-29709.appspot.com',
    iosClientId: '599903397080-mf3q4b1kbo0bi3mblp8bouktkkkmb8ce.apps.googleusercontent.com',
    iosBundleId: 'com.example.intelligentcounter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfO806O1GAHG7UAlbg5E828uLLCy2C4LI',
    appId: '1:599903397080:ios:3a99e2de7fcfae74d3e3ad',
    messagingSenderId: '599903397080',
    projectId: 'intelligentcounter-29709',
    databaseURL: 'https://intelligentcounter-29709-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'intelligentcounter-29709.appspot.com',
    iosClientId: '599903397080-6uplf8v2i9crvft8j7inq8eks5v0ilc8.apps.googleusercontent.com',
    iosBundleId: 'com.example.intelligentcounter.RunnerTests',
  );
}
